name: Perform Release

on: workflow_call

jobs:
  perform-release:
    name: Perform Release
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      BRANCH: ${{ github.ref_name }}
      TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: spring-io/spring-gradle-build-action@v2
      - id: project-version
        name: Extract Project Version
        run: echo "version=$(cat gradle.properties | grep 'version=' | awk -F'=' '{print $2}')" >> $GITHUB_OUTPUT
      - name: Fail
        if: ${{ inputs.job-to-fail == 'perform-release' }}
        run: exit 1
  next-development-version:
    name: Next Development Version
    runs-on: ubuntu-latest
    needs: [ perform-release ]
    steps:
      - name: Perform Release
        run: sleep 10 && echo 'Hello, world'
      - name: Fail
        if: ${{ inputs.job-to-fail == 'next-development-version' }}
        run: exit 1
